import vectorbt as vbt
import pandas as pd
import logging

logger = logging.getLogger(__name__)

class Backtester:
    def __init__(self):
        pass

    def run_simple_strategy(self, data, rsi_window=14, entry_rsi=30, exit_rsi=70):
        """
        Runs a simple RSI-based backtest using vectorbt.
        """
        if data.empty:
            logger.warning("No data provided for backtesting.")
            return None

        # Calculate RSI
        rsi = vbt.RSI.run(data['close'], window=rsi_window)
        
        # Define entry and exit signals
        entries = rsi.rsi_below(entry_rsi)
        exits = rsi.rsi_above(exit_rsi)
        
        # Run portfolio backtest
        pf = vbt.Portfolio.from_signals(data['close'], entries, exits, init_cash=10000)
        
        logger.info(f"Backtest complete. Total Return: {pf.total_return():.2%}")
        return pf.stats()

    def run_custom_backtest(self, df, signals):
        """
        Runs a backtest based on custom signals generated by our ResearchAnalyser.
        """
        # signals should be a boolean series
        pf = vbt.Portfolio.from_signals(df['close'], entries=signals, exits=~signals, init_cash=10000)
        return pf.stats()



